import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import ReactQueryContext from '@/presentation/context/ReactQueryContext';

import '@/presentation/styles/index.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryContext>
          <div className="max-w-[450px] mx-auto">{children}</div>
        </ReactQueryContext>
      </body>
    </html>
  );
}
